title: phishikyu's portfolio site
description: phishi website
theme: just-the-docs

url: https://phishi.dev

aux_links:
  GitHub: https://github.com/phishikyu

logo: "/assets/images/Logo-Placeholder.png"
favicon_ico: "/assets/images/Logo-Placeholder.png"

# Toggle search
search_enabled: false

# Toggle nav
nav_enabled: true

# Toggle Heading Anchor Links
heading_anchors: true

# Theme
color_scheme: light
